# Generated by Django 2.0.10 on 2019-01-10 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('user', models.IntegerField(choices=[('0', 'Mamina'), ('1', 'Kengo')])),
                ('progress', models.IntegerField(default=0)),
                ('to_be_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('to_be_complete_date', models.DateTimeField(blank=True, null=True)),
                ('memo', models.CharField(blank=True, max_length=100, null=True)),
                ('complete_date', models.DateTimeField(blank=True, null=True)),
                ('update_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
